---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-client-ca
  labels:
    app.kubernetes.io/name: kube-client-ca
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-client-ca
  labels:
    app.kubernetes.io/name: kube-client-ca
rules:
- apiGroups: [""]
  resources: [services]
  verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-client-ca
  labels:
    app.kubernetes.io/name: kube-client-ca
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-client-ca
subjects:
- kind: ServiceAccount
  name: kube-client-ca
---
apiVersion: v1
kind: Service
metadata:
  name: kube-client-ca-host
  labels:
    app.kubernetes.io/name: kube-client-ca
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: kube-client-ca
  ports:
  - name: api
    port: 9000
    nodePort: 9000
    targetPort: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-client-ca
  labels:
    app.kubernetes.io/name: kube-client-ca
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-client-ca
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-client-ca
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      serviceAccountName: kube-client-ca
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: setup-kube-client-ca-config
        image: ghcr.io/andsens/k8sss-bootstrap:0.1.1
        command: [/home/step/scripts/setup-kube-client-ca-config.sh]
        securityContext:
          readOnlyRootFilesystem: true
        env:
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: scripts
          mountPath: /home/step/scripts
        - name: config
          mountPath: /home/step/config-ro
        - name: authorized-keys
          mountPath: /home/step/admin_keys
          readOnly: true
        - name: kube-client-ca-cert
          mountPath: /home/step/kube-api-secrets/kube_apiserver_client_ca.crt
          readOnly: true
        - name: kube-client-ca-key
          mountPath: /home/step/kube-api-secrets/kube_apiserver_client_ca_key
          readOnly: true
        - name: secrets
          mountPath: /home/step/secrets
        - name: config-rw
          mountPath: /home/step/config
      containers:
      - name: step-ca
        image: cr.step.sm/smallstep/step-ca:0.27.2
        command: [/usr/local/bin/step-ca]
        args: [/home/step/config/ca.json]
        securityContext:
          readOnlyRootFilesystem: true
        ports:
        - name: api
          containerPort: 9000
        livenessProbe:
          httpGet:
            path: /health
            port: api
            scheme: HTTPS
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: api
            scheme: HTTPS
          initialDelaySeconds: 5
        volumeMounts:
        - name: secrets
          mountPath: /home/step/secrets
          readOnly: true
        - name: templates
          mountPath: /home/step/templates
        - name: config-rw
          mountPath: /home/step/config
        - name: database
          mountPath: /home/step/db
      volumes:
      - name: scripts
        configMap:
          name: kube-client-ca-scripts
          defaultMode: 0755
      - name: config
        configMap:
          name: kube-client-ca-config
      - name: authorized-keys
        hostPath:
          path: /home/admin/.ssh/authorized_keys
          type: File
      - name: templates
        configMap:
          name: kube-client-ca-templates
      - name: secrets
        emptyDir:
          medium: Memory
      - name: kube-client-ca-cert
        hostPath:
          path: /var/lib/rancher/k3s/server/tls/client-ca.crt
          type: File
      - name: kube-client-ca-key
        hostPath:
          path: /var/lib/rancher/k3s/server/tls/client-ca.key
          type: File
      - name: config-rw
        emptyDir: {}
      - name: database
        emptyDir: {}
